// client/components/navigation/Navbar.tsx
import * as React from 'react';
import Link from 'next/link';

const Navbar: React.FC = () => {
  return (
    <header className="bg-white w-screen text-gray-700 body-font">
      <div className="container mx-auto flex flex-wrap p-4 flex-col md:flex-row items-center">
        <Link href="/">
          <a className="flex title-font font-semibold items-center text-gray-900 mb-4 md:mb-0">
            <img
              className="w-10"
              src={require('../../public/logo.svg')}
              alt="Contest Pug Logo"
            />
            <span className="ml-3 text-xl">Contest Pug</span>
          </a>
        </Link>
        <nav className="md:ml-auto flex flex-wrap items-center text-base justify-center">
          <Link href="/">
            <a className="mr-8 hover:text-gray-900">Our Message</a>
          </Link>
          <Link href="/team">
            <a className="mr-8 hover:text-gray-900">Our Team</a>
          </Link>
          <Link href="/login">
            <a className="mr-8 hover:text-gray-900">Login</a>
          </Link>
        </nav>
        <Link href="/register">
          <a className="inline-flex items-center bg-primary shadow-outline-blue text-white border-0 py-2 px-20 md:px-4 transition ease-in-out duration-500 hover:shadow-md focus:outline-none rounded text-base mt-4 md:mt-0">
            Get Started
          </a>
        </Link>
      </div>
    </header>
  );
};

export default Navbar;

// client/src/components/navigation/Navbar.vue
<template>
  <header class="bg-white w-screen text-gray-700 body-font">
    <div class="container mx-auto flex flex-col md:flex-row p-4 items-center">
      <div class="flex w-full md:w-48">
        <router-link
          to="/"
          class="flex title-font font-semibold items-center text-gray-900 mb-4 md:mb-0"
        >
          <img
            class="w-10"
            src="../../assets/logo.svg"
            alt="Contest Pug Logo"
          />
          <span class="ml-3 text-xl">Contest Pug</span>
        </router-link>
        <div
          class="flex items-center justify-center rounded-lg w-12 h-12 transition ease-in duration-500 hover:bg-gray-200 md:hidden ml-auto mb-2 text-gray-600 cursor-pointer"
          @click="toggleNavbar"
        >
          <svg
            viewBox="0 0 20 20"
            fill="currentColor"
            class="menu-alt3 w-6 h-6"
          >
            <path
              fill-rule="evenodd"
              d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM9 15a1 1 0 011-1h6a1 1 0 110 2h-6a1 1 0 01-1-1z"
              clip-rule="evenodd"
            ></path>
          </svg>
        </div>
      </div>
      <nav
        :class="[
          showNavbar ? 'flex' : 'hidden',
          'md:ml-auto md:flex flex-wrap items-center text-base justify-center',
        ]"
      >
        <router-link to="/" class="mr-8 hover:text-gray-900">
          Our Message
        </router-link>
        <router-link to="/team" class="mr-8 hover:text-gray-900">
          Our Team
        </router-link>
        <router-link to="/login" class="mr-8 hover:text-gray-900">
          Login
        </router-link>
        <router-link
          to="/register"
          class="inline-flex items-center md:bg-primary md:shadow-outline-blue md:text-white border-0 py-3 md:py-2 md:px-4 md:hover:shadow-md focus:outline-none rounded text-base"
        >
          Get Started
        </router-link>
      </nav>
    </div>
  </header>
</template>

<script lang="ts">
import { ref, defineComponent } from '@vue/composition-api';

export default defineComponent({
  name: 'Navbar',
  setup() {
    const showNavbar = ref(false);
    const toggleNavbar = () => (showNavbar.value = !showNavbar.value);
    return {
      showNavbar,
      toggleNavbar,
    };
  },
});
</script>
